/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        space: '#050508',
        'space-2': '#0d0b14',
        violet: { DEFAULT: '#7C3AED', light: '#A855F7', dark: '#5B21B6', glow: '#8B5CF6' },
        gold: { DEFAULT: '#F59E0B', light: '#FCD34D' },
        'soft-white': '#F8F8FF',
      },
      fontFamily: {
        heading: ['"Instrument Serif"', 'Georgia', 'serif'],
        sub: ['"DM Sans"', 'system-ui', 'sans-serif'],
        body: ['"Inter"', 'system-ui', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      animation: {
        'float-a': 'floatA 10s ease-in-out infinite',
        'float-b': 'floatB 13s ease-in-out infinite',
        'float-c': 'floatC 8s ease-in-out infinite',
        'pulse-glow': 'pulseGlow 3s ease-in-out infinite',
        'marquee': 'marquee 40s linear infinite',
        'marquee-rev': 'marqueeRev 40s linear infinite',
        'grain': 'grain 0.4s steps(1) infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'spin-slow': 'spin 25s linear infinite',
        'border-spin': 'borderSpin 4s linear infinite',
      },
      keyframes: {
        floatA: { '0%,100%': { transform: 'translate(0,0) scale(1)' }, '33%': { transform: 'translate(40px,-50px) scale(1.05)' }, '66%': { transform: 'translate(-20px,20px) scale(0.97)' } },
        floatB: { '0%,100%': { transform: 'translate(0,0)' }, '50%': { transform: 'translate(-35px,45px)' } },
        floatC: { '0%,100%': { transform: 'translate(0,0)' }, '50%': { transform: 'translate(25px,-30px)' } },
        pulseGlow: { '0%,100%': { opacity: '0.5', transform: 'scale(1)' }, '50%': { opacity: '1', transform: 'scale(1.08)' } },
        marquee: { '0%': { transform: 'translateX(0)' }, '100%': { transform: 'translateX(-50%)' } },
        marqueeRev: { '0%': { transform: 'translateX(-50%)' }, '100%': { transform: 'translateX(0)' } },
        grain: {
          '0%,100%': { transform: 'translate(0,0)' },
          '10%': { transform: 'translate(-2%,-3%)' },
          '20%': { transform: 'translate(3%,1%)' },
          '30%': { transform: 'translate(-1%,4%)' },
          '40%': { transform: 'translate(2%,-2%)' },
          '50%': { transform: 'translate(-3%,3%)' },
          '60%': { transform: 'translate(1%,-4%)' },
          '70%': { transform: 'translate(-2%,2%)' },
          '80%': { transform: 'translate(4%,-1%)' },
          '90%': { transform: 'translate(-1%,3%)' },
        },
        shimmer: { '0%': { backgroundPosition: '-400% 0' }, '100%': { backgroundPosition: '400% 0' } },
        borderSpin: { '0%': { '--angle': '0deg' }, '100%': { '--angle': '360deg' } },
      },
      boxShadow: {
        'gv': '0 0 40px rgba(124,58,237,0.5), 0 0 80px rgba(124,58,237,0.2)',
        'gv-sm': '0 0 20px rgba(124,58,237,0.4)',
        'gg': '0 0 30px rgba(245,158,11,0.35)',
        'card': '0 4px 32px rgba(0,0,0,0.5)',
        'card-h': '0 8px 48px rgba(124,58,237,0.25), 0 4px 16px rgba(0,0,0,0.6)',
      },
    },
  },
  plugins: [],
}
